
spring:
  datasource:
    # database username
    username: xxx
    # username password
    password: xxx
    # JDBC URL
    url: jdbc:postgresql://localhost:5432/bookdb
    # JDBC driver name
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.jdbi: DEBUG